apiVersion: v1
kind: Pod
metadata:
  name: golang-pod1
  labels:
    name: golang-app
spec:
  containers:
  - name: golang-app1
    image: jhonatanlteodoro/go_app1:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "200m"
    ports:
      - containerPort: 8080
