apiVersion: v1
kind: Pod
metadata:
  name: python-pod
  labels:
    name: python-app
spec:
  containers:
  - name: python-app
    image: jhonatanlteodoro/app_python:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "200m"
    ports:
      - containerPort: 5000
