apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc-postgresql
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-storage
